### PR TITLE
use ast/re instead of import to get version in setup.py

### PR DESCRIPTION
**Pull request by Ohjeah**

### CODE REVIEW

**Comment by jknox13** [comment]
I like this a lot as it better conforms to [#1](https://packaging.python.org/guides/single-sourcing-package-version/).

Can you fix the 2.7 incompatibility with the `encoding` keyword argument to the `open` function. I think importing `open` from `io` should work. See [here](https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2) for some ideas.

**Comment by jknox13** [comment]
Or maybe a better idea is to forget about the encoding and run

**Comment by Ohjeah** [comment]
@jknox13 Should work now. Forgot about the backwards compatibility :)

**Comment by erichson** [comment]
That is great! Thank you very much.

**Pull request merged**
